---
- name: Install and configure Bind9 DNS server
  hosts: dnsServer
  become: true
  tasks:
    - name: Check health status of DNS server
      ansible.builtin.ping:

    - name: Update the server's cache
      apt:
        update_cache: yes

    - name: Install Bind9
      apt:
        name:
